# Generated by Django 4.2.1 on 2023-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_job_about_company_job_bonus_skills_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='name_company',
            field=models.CharField(default='', max_length=255),
        ),
    ]
